// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiesgosElor.Data;

#nullable disable

namespace RiesgosElor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706145106_AddMatrizGrupoFix")]
    partial class AddMatrizGrupoFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiesgosElor.Models.CambioPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHashAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CambiosPassword");
                });

            modelBuilder.Entity("RiesgosElor.Models.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoKRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinicionKRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KRIActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableKRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiesgoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiesgoId");

                    b.ToTable("Indicadores");
                });

            modelBuilder.Entity("RiesgosElor.Models.MatrizEncabezado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprobadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AprobadoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMatriz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaboradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaboradoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaAprobacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatrizNivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisadoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionMatriz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatrizEncabezados");
                });

            modelBuilder.Entity("RiesgosElor.Models.MatrizGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprobadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AprobadoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoMatriz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaboradoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElaboradoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaAprobacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatrizNivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("RevisadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisadoPorFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionMatriz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatrizGrupos");
                });

            modelBuilder.Entity("RiesgosElor.Models.PlanAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstrategiaRespuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinPlan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InicioPlan")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsablePlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiesgoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiesgoId");

                    b.ToTable("PlanesAccion");
                });

            modelBuilder.Entity("RiesgosElor.Models.Riesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstrategiaResidual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrecuenciaRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerenciaResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpactoInherente")
                        .HasColumnType("int");

                    b.Property<int>("ImpactoResidual")
                        .HasColumnType("int");

                    b.Property<int?>("MatrizGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProbabilidadInherente")
                        .HasColumnType("int");

                    b.Property<int>("ProbabilidadResidual")
                        .HasColumnType("int");

                    b.Property<string>("Subproceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatrizGrupoId");

                    b.ToTable("Riesgos");
                });

            modelBuilder.Entity("RiesgosElor.Models.RiesgoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaResponsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutomatizacionControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrecuenciaControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OportunidadControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsablesControl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiesgoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiesgoId");

                    b.ToTable("RiesgosControl");
                });

            modelBuilder.Entity("RiesgosElor.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RiesgosElor.Models.CambioPassword", b =>
                {
                    b.HasOne("RiesgosElor.Models.Usuario", "Usuario")
                        .WithMany("CambiosPassword")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RiesgosElor.Models.Indicador", b =>
                {
                    b.HasOne("RiesgosElor.Models.Riesgo", "Riesgo")
                        .WithMany("Indicadores")
                        .HasForeignKey("RiesgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("RiesgosElor.Models.PlanAccion", b =>
                {
                    b.HasOne("RiesgosElor.Models.Riesgo", "Riesgo")
                        .WithMany("PlanesAccion")
                        .HasForeignKey("RiesgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("RiesgosElor.Models.Riesgo", b =>
                {
                    b.HasOne("RiesgosElor.Models.MatrizGrupo", "MatrizGrupo")
                        .WithMany("Riesgos")
                        .HasForeignKey("MatrizGrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatrizGrupo");
                });

            modelBuilder.Entity("RiesgosElor.Models.RiesgoControl", b =>
                {
                    b.HasOne("RiesgosElor.Models.Riesgo", "Riesgo")
                        .WithMany("Controles")
                        .HasForeignKey("RiesgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riesgo");
                });

            modelBuilder.Entity("RiesgosElor.Models.MatrizGrupo", b =>
                {
                    b.Navigation("Riesgos");
                });

            modelBuilder.Entity("RiesgosElor.Models.Riesgo", b =>
                {
                    b.Navigation("Controles");

                    b.Navigation("Indicadores");

                    b.Navigation("PlanesAccion");
                });

            modelBuilder.Entity("RiesgosElor.Models.Usuario", b =>
                {
                    b.Navigation("CambiosPassword");
                });
#pragma warning restore 612, 618
        }
    }
}
